import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SYMBOLS_DIR = join(import.meta.dir, '..', 'packages', 'core', 'src', 'preview', 'symbols');
const OUT_FILE = join(SYMBOLS_DIR, 'svg-content.ts');

const files = readdirSync(SYMBOLS_DIR)
    .filter((f) => f.endsWith('.svg'))
    .sort();

const entries: string[] = [];
const innerRegex = /<svg[^>]*>([\s\S]*?)<\/svg>/;

for (const file of files) {
    const key = file.replace(/\.svg$/, '');
    const raw = readFileSync(join(SYMBOLS_DIR, file), 'utf8');
    const match = raw.match(innerRegex);
    if (match === null) {
        throw new Error(`${file}: no <svg>…</svg> body found`);
    }
    const inner = match[1]?.trim();
    if (inner === undefined) {
        throw new Error(`${file}: no <svg>…</svg> body found`);
    }
    const viewBoxMatch = raw.match(/viewBox="([^"]+)"/);
    const viewBox = viewBoxMatch?.[1] ?? '-25 -25 50 50';
    entries.push(
        `    ${JSON.stringify(key)}: { viewBox: ${JSON.stringify(viewBox)}, content: ${JSON.stringify(inner)} }`,
    );
}

const header = `// AUTO-GENERATED by scripts/generate-symbol-content.ts — DO NOT EDIT BY HAND.
// Run \`bun run generate:symbols\` to regenerate from packages/core/src/preview/symbols/*.svg.

export type SymbolContent = Readonly<{ viewBox: string; content: string }>;

export const SYMBOL_CONTENT: Readonly<Record<string, SymbolContent>> = {
${entries.join(',\n')},
};

export const SYMBOL_KEYS = Object.keys(SYMBOL_CONTENT) as readonly string[];
`;

writeFileSync(OUT_FILE, header);
console.log(`Wrote ${OUT_FILE} (${files.length} symbols)`);
